pipeline:

  build_10:
    image: node:10
    commands:
      - npm --loglevel warn install
      - npm run test
    when:
      event: [push, pull_request]

  build_app:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t app-$${DRONE_COMMIT_SHA} .
    when:
      event: pull_request

  build_app:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t app-$${DRONE_COMMIT_SHA} .
    when:
      branch: master
      event: push

  build_acceptance:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -f Dockerfile-acceptance -t acceptance-$${DRONE_COMMIT_SHA} .
    when:
      event: pull_request

  build_acceptance:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -f Dockerfile-acceptance -t acceptance-$${DRONE_COMMIT_SHA} .
    when:
      branch: master
      event: push

  test_acceptance:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker run -d --name=redis-$${DRONE_COMMIT_SHA} redis
      - docker run -d -e NODE_ENV=ci -e DISABLE_CSP=true -e EMAIL_TRANSPORT=stub -e CASEWORKER_EMAIL=test@example.com --net=container:redis-$${DRONE_COMMIT_SHA} --name=app-$${DRONE_COMMIT_SHA} app-$${DRONE_COMMIT_SHA}
      - docker run -d --net=container:app-$${DRONE_COMMIT_SHA} --name=selenium-$${DRONE_COMMIT_SHA} selenium/standalone-chrome
      - sleep 5
      - docker run --rm -e NODE_ENV=ci -e DISABLE_CSP=true -e EMAIL_TRANSPORT=stub -e CASEWORKER_EMAIL=test@example.com --net=container:app-$${DRONE_COMMIT_SHA} acceptance-$${DRONE_COMMIT_SHA}
      - docker rm -vf "app-$${DRONE_COMMIT_SHA}" "redis-$${DRONE_COMMIT_SHA}" "selenium-$${DRONE_COMMIT_SHA}"
    when:
      event: pull_request

  test_acceptance:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker run -d --name=redis-$${DRONE_COMMIT_SHA} redis
      - docker run -d -e NODE_ENV=ci -e DISABLE_CSP=true -e EMAIL_TRANSPORT=stub -e CASEWORKER_EMAIL=test@example.com --net=container:redis-$${DRONE_COMMIT_SHA} --name=app-$${DRONE_COMMIT_SHA} app-$${DRONE_COMMIT_SHA}
      - docker run -d --net=container:app-$${DRONE_COMMIT_SHA} --name=selenium-$${DRONE_COMMIT_SHA} selenium/standalone-chrome
      - sleep 5
      - docker run --rm -e NODE_ENV=ci -e DISABLE_CSP=true -e EMAIL_TRANSPORT=stub -e CASEWORKER_EMAIL=test@example.com --net=container:app-$${DRONE_COMMIT_SHA} acceptance-$${DRONE_COMMIT_SHA}
      - docker rm -vf "app-$${DRONE_COMMIT_SHA}" "redis-$${DRONE_COMMIT_SHA}" "selenium-$${DRONE_COMMIT_SHA}"
    when:
      branch: master
      event: push

  image_to_quay:
    image: docker:17.09.1
    secrets:
      - DOCKER_PASSWORD
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag app-$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/rent-check:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/rent-check:$${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  trigger_deploy_to_rent-check_dev:
    image: quay.io/ukhomeofficedigital/drone-trigger:v0.3.0
    secrets:
      - DRONE_TOKEN
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/kube-right-to-rent
    branch: master
    deploy_to: dev
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=rent-check-dev
    when:
      branch: master
      event: push

  trigger_deploy_to_rent-check_preprod:
    image: quay.io/ukhomeofficedigital/drone-trigger:v0.3.0
    secrets:
      - DRONE_TOKEN
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/kube-right-to-rent
    branch: master
    deploy_to: preprod
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=rent-check-preprod
    when:
      event: deployment
      environment: preprod

  trigger_deploy_to_rent-check_prod:
    image: quay.io/ukhomeofficedigital/drone-trigger:v0.3.0
    secrets:
      - DRONE_TOKEN
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/kube-right-to-rent
    branch: master
    deploy_to: prod
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=rent-check
    when:
      event: deployment
      environment: prod
