pipeline:
  build_4:
    image: node:4.4.2
    commands:
      - npm --loglevel warn install -g npm@3
      - npm --loglevel warn install
      - npm run test

  build_5:
    image: node:5
    commands:
      - npm --loglevel warn install
      - npm run test

  build_app:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build --no-cache -t app .

  build_acceptance:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build --no-cache -f Dockerfile-acceptance -t acceptance .

  test_acceptance:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker run -e NODE_ENV=ci -e DISABLE_CSP=true -e POSTCODE_AUTH=${POSTCODE_AUTH} -d --net host app
      - docker run --rm --net host acceptance

  image_to_quay:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=${DOCKER_PASSWORD} quay.io
      - docker tag app quay.io/ukhomeofficedigital/rent-check:${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/rent-check:${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  trigger_deploy_to_rent-check_dev:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    drone_server: https://drone.digital.homeoffice.gov.uk
    repo: UKHomeOffice/kube-right-to-rent
    branch: master
    deploy_to: rent-check-dev
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=rent-check-dev
    when:
      branch: master
      event: push

  trigger_deploy_to_rent-check_preprod:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    drone_server: https://drone.digital.homeoffice.gov.uk
    repo: UKHomeOffice/kube-right-to-rent
    branch: master
    deploy_to: rent-check-preprod
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=rent-check-preprod
    when:
      event: tag

services:
  redis:
    image: redis
  dind:
    image: docker:1.11-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
