pipeline:

  build_6:
    image: node:6
    commands:
      - npm --loglevel warn install
      - npm run test

  build_8:
    image: node:8
    commands:
      - npm --loglevel warn install
      - npm run test

  build_app:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t app .
    when:
      event: pull_request

  build_app:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t app .
    when:
      branch: master

  build_acceptance:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -f Dockerfile-acceptance -t acceptance .
    when:
      event: pull_request

  build_acceptance:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -f Dockerfile-acceptance -t acceptance .
    when:
      branch: master

  test_acceptance:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker run -e NODE_ENV=ci -e DISABLE_CSP=true -e EMAIL_TRANSPORT=stub -d --net host app
      - docker run --rm --net host acceptance
    when:
      event: pull_request

  test_acceptance:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker run -e NODE_ENV=ci -e DISABLE_CSP=true -d --net host app
      - docker run --rm --net host acceptance
    when:
      branch: master

  image_to_quay:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+serviceops" -p=${DOCKER_PASSWORD} quay.io
      - docker tag app quay.io/ukhomeofficedigital/rent-check:${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/rent-check:${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  trigger_deploy_to_rent-check_dev:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    drone_server: https://drone.digital.homeoffice.gov.uk
    repo: UKHomeOffice/kube-right-to-rent
    branch: master
    deploy_to: rent-check-dev
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=rent-check-dev
    when:
      branch: master
      event: push

  trigger_deploy_to_rent-check_preprod:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    drone_server: https://drone.digital.homeoffice.gov.uk
    repo: UKHomeOffice/kube-right-to-rent
    branch: master
    deploy_to: rent-check-preprod
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=rent-check-preprod
    when:
      event: tag

services:
  redis:
    image: redis
  dind:
    image: docker:1.11-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
