language: node_js
node_js:
  - "6"
  - "5"
  - "4.4.2"

services:
  - docker
  - redis

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm cache clean

script:
  - npm run build
  - npm test
